apiVersion: v1
kind: Service
metadata:
  name: go-gke-alloydb
  labels:
    app: go-gke-alloydb
spec:
  type: LoadBalancer
  selector:
    app: go-gke-alloydb
  ports:
    - name: http
      port: 80
      targetPort: http
