apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - serviceaccount.yaml
  - configmap.yaml

images:
  - name: app-image
    newName: us-central1-docker.pkg.dev/PROJECT_ID/REPOSITORY/go-gke-alloydb
    newTag: latest

patches:
  - path: deployment-patch.yaml
