apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-gke-alloydb
  annotations:
    iam.gke.io/gcp-service-account: go-gke-alloydb@PROJECT_ID.iam.gserviceaccount.com
    iam.gke.io/return-principal-id-as-email: "true"
