// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const databasePing = `-- name: DatabasePing :one
SELECT 'pong'::text AS message
`

func (q *Queries) DatabasePing(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, databasePing)
	var message string
	err := row.Scan(&message)
	return message, err
}
